name: deploy functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci

    - name: Deploy
      uses: serverless/github-action@master
      with:
        args: -c "serverless plugin install --name serverless deploy --region us-east-1 --verbose"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SERVERLESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_SERVERLESS }}